title: Headers
hidden: false
order: 10
status: wip

variants:
  - name: default
    label: UIowa Bar Full
    hidden: false
    context:
      site_name: Site Name
      site_slogan: slogan
      site_title:
      header_nav:
      header_type: header--secondary
      header_action:
  - name: UIowa Bar Small
    label: UIowa Bar Small
    hidden: false
    context:
      site_name:
      site_slogan: Carver College of Medicine
      site_title:
      header_nav:
      header_type: header--tertiary
      header_action:
  - name: UIowa Bar Simple
    label: UIowa Bar Simple
    hidden: False
    context:
      site_name:
      site_slogan:
      site_title:
      header_nav:
      header_type: header--tertiary
