title: WYSIWYG Classes
order: 1
status: wip
context:
    heading_6: <p class="h6">Heading 6</p>
    heading_5: <p class="h5">Heading 5</p>
    heading_4: <p class="h4">Heading 4</p>
    heading_3: <p class="h3">Heading 3</p>
    heading_2: <p class="h2">Heading 2</p>
    heading_1: <p class="h1">Heading 1</p>
    circle_list: <ul class="uids-component--circle-list"><li>In fermentum leo eu lectus mollis, quis dictum mi aliquet.</li><li>Morbi eu nulla lobortis, lobortis est in, fringilla felis.</li><li>Aliquam nec felis in sapien venenatis viverra fermentum nec lectus.</li><li>Ut non enim metus.</li></ul>
    bold_headline_caps: <h2 class="bold-headline bold-headline--caps">Bold Headline Caps</h2>
    bold_headline_serif: <h2 class="bold-headline bold-headline--serif">Bold Headline Serif</h2>
    bold_headline_serif_underline: <h2 class="bold-headline bold-headline--serif bold-headline--underline">Bold Headline Serif Underlined</h2>
    striped_table: <table class="table is-striped"><caption class="element-invisible">Tablescanhavecaptionsnow.</caption><thead><tr><th>Person</th><th>Number</th><th>ThirdColumn</th></tr></thead><tbody><tr><td>SomeoneLastname</td><td>900</td><td>Nullamquisrisusegeturnamollisornareveleuleo.</td></tr><tr><td><ahref="#">PersonName</a></td><td>1200</td><td>Vestibulumidligulaportafeliseuismodsemper.Donecullamcorpernullanonmetusauctorfringilla.</td></tr><tr><td>AnotherPerson</td><td>1500</td><td>Vivamussagittislacusvelauguelaoreetrutrumfaucibusdolorauctor.Nullamiddoloridnibhultriciesvehiculautidelit.</td></tr><tr><td>LastOne</td><td>2800</td><td>Morbileorisus,portaacconsecteturac,vestibulumateros.Crasmattisconsecteturpurussitametfermentum.</td></tr></tbody></table>
