title: Portraits Block
hidden: false
order: 3
status: wip
context:
  portrait:
    items:
      - portrait_title: Kelly
        portrait_sub: Business, 2019
        portrait_link: ../../video/kelly.mp4
        portrait_srt: ../../video/kelly.srt
        portrait_poster: ../../video/kelly.png
      - portrait_title: Study
        portrait_sub: Accounting, 2019
        portrait_link: ../../video/study.mp4
        portrait_srt: ../../video/study.srt
        portrait_poster: ../../video/study.png
      - portrait_title: Vikings
        portrait_sub: PsyVichology, 2019
        portrait_link: ../../video/vikings.mp4
        portrait_srt: ../../video/vikings.srt
        portrait_poster: ../../video/vikings.png
