title: Headers
hidden: false
order: 10
status: wip

variants:
  - name: default
    label: UIowa Primary Header
    hidden: false
    context:
      site_name:
      site_slogan:
      site_title:
      header_nav: header--toggle
      header_type: header--primary
      header_action: header--sticky
  - name: Site Name with off-canvas
    label: UIowa Secondary Header
    hidden: false
    context:
      site_name: Carver College of Medicine
      site_slogan:
      site_title:
      header_nav: header--toggle
      header_type: header--secondary
      header_action: header--sticky
  - name: Site Name with Subnav
    label: UIowa Secondary Header subnav
    hidden: false
    context:
      site_name: Carver College of Medicine
      site_slogan:
      site_title:
      header_nav: header--horizontal
      header_type: header--secondary
      header_action:
  - name: Department Nav with off-canvas
    label: UIowa Tertiary Header
    hidden: false
    context:
      site_name: Fraternal Order of Eagles Diabetes Research Center
      site_slogan: Carver College of Medicine
      site_title:
      header_nav: header--toggle
      header_type: header--tertiary
      header_action: header--sticky
  - name: Department Nav
    label: UIowa Tertiary Header with subnav
    hidden: false
    context:
      site_name: Fraternal Order of Eagles Diabetes Research Center
      site_slogan: Carver College of Medicine
      site_title:
      header_nav: header--horizontal
      header_type: header--tertiary
