title: Headers
hidden: false
order: 10
status: wip

variants:
  - name: default
    label: UIowa Primary Header
    hidden: false
    context:
      site_name:
      site_slogan:
      site_front:
      site_title:
      site_nav: off-canvas
      top_nav: uiowa
      header_classes: main-iowa
      header_type: header--primary
  - name: Site Name with off-canvas
    label: UIowa Secondary Header
    hidden: false
    context:
      site_name: Carver College of Medicine
      site_slogan:
      site_front:
      site_title:
      site_nav: off-canvas
      top_nav: none
      header_classes: top-iowa
      header_type: header--secondary
  - name: Site Name with Subnav
    label: UIowa Secondary Header subnav
    hidden: false
    context:
      site_name: Carver College of Medicine
      site_slogan:
      site_front:
      site_title:
      site_nav: horizontal
      site_subnav: subnav-true
      top_nav: none
      header_classes: top-iowa
      header_type: header--secondary
  - name: Department Nav with off-canvas
    label: UIowa Tertiary Header
    hidden: false
    context:
      site_name: Fraternal Order of Eagles Diabetes Research Center
      site_slogan: Carver College of Medicine
      site_front:
      site_title:
      site_nav: off-canvas
      site_subnav: subnav-false
      top_nav: department
      header_classes: dept-menu
      header_type: header--tertiary
  - name: Department Nav
    label: UIowa Tertiary Header with subnav
    hidden: false
    context:
      site_name: Fraternal Order of Eagles Diabetes Research Center
      site_slogan: Carver College of Medicine
      site_front:
      site_title:
      site_nav: horizontal
      site_subnav: subnav-true
      top_nav: department
      header_classes: dept-menu
      header_type: header--tertiary
