sudo: false

language: node_js

# Use .nvmrc file for Node version.
node_js:

matrix:
  fast_finish: true

install:
- npm install

script:
- npm run build

before_deploy:
  - rm -rf assets/ components/ dist/ documentation/
  - rm config.json fractal.js gulpfile.js package.json package-lock.json README.md
  - mv -v docs/* .

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  on:
    branch: master