title: Card
status: prototype
order: 3
hidden: false
context:
  card_title: Dedicated to having an impact on human health
  card_link_title: View Story
  card_link_url: https://uiowa.edu/
  card_image: ../../images/feature1.jpg
  card_content: <p>Molecular <a href="https://hr.uiowa.edu">medicine PhD</a> student Jordan Kohlmeyer is researching new therapies for malignant peripheral nerve sheath tumors, which are deadly, resistant to drug therapies, and often unable to be operated upon due to their location.</p>
  card_date: June 14, 1984
  card_author: By Lee Hermiston
  card_type: card--open
  card_aria: desc-a-card
display:
  max-width: 500px
variants:
  - name: default
    label: Default
  - name: no_link
    label: Without link
    title: Card without link
    context:
      card_link_title: ''
      card_link_url: ''
  - name: image_only
    label: Image only
    context:
      card_title: ''
      card_content: ''
      card_date: ''
      card_author: ''
  - name: image_only_no_link
    context:
      card_title: ''
      card_link_title: ''
      card_link_url: ''
      card_content: ''
      card_date: ''
      card_author: ''
