title: Card
status: prototype
order: 3
hidden: false
context:
  card_title: Dedicated to having an impact on human health
  card_link_title: View Story
  card_link_url: https://uiowa.edu/
  card_image: ../../images/feature1.jpg
  card_content: <p>Molecular <a href="https://hr.uiowa.edu">medicine PhD</a> student Jordan Kohlmeyer is researching new therapies for malignant peripheral nerve sheath tumors, which are deadly, resistant to drug therapies, and often unable to be operated upon due to their location.</p>
  card_date: June 14, 1984
  card_author: By Lee Hermiston
  card_aria: desc-a-card
display:
  max-width: 500px
variants:
  - name: default
    label: Vertical
  - name: no_link
    label: Vertical w/o link
    context:
      card_link_title: ''
      card_link_url: ''
  - name: no_image
    label: Vertical w/o image
    context:
      card_image: ''
  - name: enclosed
    label: Enclosed
    context:
      card_classes: 'card--enclosed'
  - name: horizontal
    label: Horizontal
    context:
      card_title: Getting to know Iowa's fall 2018 graduates
      card_image: ../../images/icon.png
      card_classes: 'card--horizontal'
      card_text: <p>Applications can be submitted via Iowa’s web application portal, the Common Application, and Coalition App. Once submitted, <a href="/">you</a> can track the status of your application through MyUI, a one-stop resource for current and prospective Iowa students.</p>
      card_date: June 14, 1984
      card_author: By the Office of Strategic Communication
    display:
      max-width: 1200px
