title: IOWA Bar
hidden: false
order: 2
status: wip

variants:
  - name: default
    label: Just logo
    hidden: false
    context:
      site_name: ''
      header_nav:
      header_type: header--tertiary
      header_action:
  - name: narrow
    label: Narrow
    hidden: false
    context:
      site_name: Site Name
      header_nav:
      header_type: header--tertiary
      header_action:
  - name: full
    label: Full
    hidden: False
    context:
      site_name: Site Name
      header_nav:
      header_type: header--secondary
