title: Background Image
order: 2
status: wip
collated: false

variants:
  - name: default
    label: Background Image
    hidden: false
    context:
      image_path_1: ../../images/widescreen__384_x_216/bg-image.jpg
      image_path_2: ../../images/widescreen__768_x_432/bg-image.jpg
      image_path_3: ../../images/widescreen__1024_x_576/bg-image.jpg
      image_path_4: ../../images/widescreen__1312_x_738/bg-image.jpg
      image_path_5: ../../images/widescreen__1920_x_1080/bg-image.jpg
      image_path_6: ../../images/widescreen__2592_x_1458/bg-image.jpg

