title: Accordions
status: wip
order: 1
hidden: false

variants:
  - name: Default
    label: Multi Select
    hidden: false
    context:
      accordion:
        multiselectable: true
        unique_id: No1
        items: 
            -   title: First amendment
                id: a1
                expanded: true
                content: |
                    <p>Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.</p>
            -   title: Second Amendment
                id: a2
                content: |
                    <p>A well regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms, shall not be infringed.</p> <ul><li>This is a list item</li><li>Another list item</li></ul>
            -   title: Third Amendment
                id: a3
                content: |
                    <p>No Soldier shall, in time of peace be quartered in any house, without the consent of the Owner, nor in time of war, but in a manner to be prescribed by law.</p>
            -   title: Fourth Amendment
                id: a4
                content: |
                    <p>The right of the people to be secure in their persons, houses, papers, and effects, against unreasonable searches and seizures, shall not be violated, and no Warrants shall issue, but upon probable cause, supported by Oath or affirmation, and particularly describing the place to be searched, and the persons or things to be seized.</p>
  
  - name: Single Select
    hidden: false
    context:
        accordion:
            multiselectable: false
            unique_id: No1
            items: 
                -   title: First amendment
                    id: a1
                    expanded: true
                    content: |
                        <p>Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.</p>
                -   title: Second Amendment
                    id: a2
                    content: |
                        <p>A well regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms, shall not be infringed.</p> <ul><li>This is a list item</li><li>Another list item</li></ul>
                -   title: Third Amendment
                    id: a3
                    content: |
                        <p>No Soldier shall, in time of peace be quartered in any house, without the consent of the Owner, nor in time of war, but in a manner to be prescribed by law.</p>
                -   title: Fourth Amendment
                    id: a4
                    content: |
                        <p>The right of the people to be secure in their persons, houses, papers, and effects, against unreasonable searches and seizures, shall not be violated, and no Warrants shall issue, but upon probable cause, supported by Oath or affirmation, and particularly describing the place to be searched, and the persons or things to be seized.</p>

context:
    accordion:
        multiselectable: true
        unique_id: No1
        items: 
            -   title: First amendment
                id: a1
                expanded: true
                content: |
                    <p>Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.</p>
            -   title: Second Amendment
                id: a2
                content: |
                    <p>A well regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms, shall not be infringed.</p> <ul><li>This is a list item</li><li>Another list item</li></ul>
            -   title: Third Amendment
                id: a3
                content: |
                    <p>No Soldier shall, in time of peace be quartered in any house, without the consent of the Owner, nor in time of war, but in a manner to be prescribed by law.</p>
            -   title: Fourth Amendment
                id: a4
                content: |
                    <p>The right of the people to be secure in their persons, houses, papers, and effects, against unreasonable searches and seizures, shall not be violated, and no Warrants shall issue, but upon probable cause, supported by Oath or affirmation, and particularly describing the place to be searched, and the persons or things to be seized.</p>
  