title: Slider
hidden: false
order: 3
status: prototype
meta:
  dependencies:
    stylesheets:
      - /components/banner/banner.css
variants:
  - name: default
    label: 3 Slides
    hidden: false
    context:
      block_type: basic
      feature_type: image
      feature_state: feature__container-expanded
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: '../../../assets/images/examples/feature1.jpg'
            feature_link: https://example.com
          - feature_title: 2019 Graduates
            feature_sub: Receiving a diploma signals both an ending and a beginning
            feature_banner_image: '../../../assets/images/examples/feature2.jpg'
            feature_link: https://example.com
          - feature_title: Turning the Tide
            feature_sub: Alumna Lauren Palmer aims to rehabilitate animals
            feature_banner_image: '../../../assets/images/examples/feature3.jpg'
            feature_link: https://example.com
  - name: 2_slides
    label: 2 Slides
    hidden: false
    context:
      block_type: basic
      feature_type: image
      feature_state: feature__container-expanded
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: '../../../assets/images/examples/feature3.jpg'
            feature_link: https://example.com
          - feature_title: 2019 Graduates
            feature_sub: Receiving a diploma signals both an ending and a beginning
            feature_banner_image: '../../../assets/images/examples/feature3.jpg'
            feature_link: https://example.com
  - name: 1_slide
    label: 1 Slide
    context:
      block_type: basic
      feature_type: image
      feature_state: feature__container-expanded
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: '../../../assets/images/examples/feature3.jpg'
            feature_link: https://example.com
  - name: slide
    hidden: true
