label: UIOWA Bar
order: 8
status: wip
hidden: true
context:
    bg_color: uiowa-bar--primary
    site_type: uiowa-bar--standard
variants:
  - name: Secondary
    hidden: true
    context:
      bg_color: uiowa-bar--secondary
      site_type: uiowa-bar--standard
  - name: Home Page A
    hidden: true
    context:
      bg_color: uiowa-bar--primary
      site_type: uiowa-bar--home
  - name: Home Page B
    hidden: true
    context:
      bg_color: uiowa-bar--primary-b
      site_type: uiowa-bar--home
  - name: Home Page C
    hidden: true
    context:
      bg_color: uiowa-bar--primary-c
      site_type: uiowa-bar--home


