title: Hero Block
order: 99
status: wip
context:
  hero_type: video
  hero_content: center
  hero_title: 'See for yourself'
  hero_image: ../../images/hero-image.jpg
  hero_image_alt: 'View of University of Iowa Campus'
  hero_video: ../../video/home.mp4
  cta:
    items:
      - text: 'Schedule a Visit'
        type: 'bttn bttn--secondary bttn--sans-serif bttn--outline bttn--outline'
        link: 'https://example.com'
      - text: 'Areas of Focus'
        type: 'bttn bttn--secondary bttn--sans-serif bttn--outline bttn--outline'
        link: 'https://example.com'
      - text: 'Cost and Aid'
        type: 'bttn bttn--secondary bttn--sans-serif bttn--outline bttn--outline'
        link: 'https://example.com'
variants:
  - name: default
    hidden: true
  - name: Hero Video Content Center
    context:
      hero_type: video
      hero_content: center
  - name: Hero Video Content Bottom
    context:
      hero_type: video
      hero_content: bottom
  - name: Hero Image Content Center
    context:
      hero_type: image
      hero_content: center
  - name: Hero Image Content Bottom
    context:
      hero_type: image
      hero_content: bottom
