title: Hero Block
order: 99
status: wip
context:
  hero_type: video
  hero_title: 'See for yourself'
  hero_image: ../../images/hero-image.jpg
  hero_image_alt: 'View of University of Iowa Campus'
  hero_video: https://tippie.uiowa.edu/sites/tippie.uiowa.edu/files/video/tippie_build1_final_720.mp4
  cta:
    items:
      - text: 'Schedule a Visit'
        type: 'bttn bttn--outline bttn--secondary__light'
        link: 'https://example.com'
      - text: 'Areas of Focus'
        type: 'bttn bttn--outline bttn--secondary__light'
        link: 'https://example.com'
      - text: 'Cost and Aid'
        type: 'bttn bttn--outline bttn--secondary__light'
        link: 'https://example.com'
variants:
  - name: Hero Video
    context:
      hero_type: video
  - name: Hero Image
    context:
      hero_type: image