title: Site Name
hidden: false
order: 9
status: wip
context:
    footer_logo: ../../images/uiowa-secondary.svg#logo
    footer_type: uiowa
    link_bttn:
      items:
      - link_bttn_title: Request Info
        link_bttn_url: https://example.com
        link_bttn_class: bttn bttn--full bttn--outline bttn--secondary__light
        link_bttn_icon:
      - link_bttn_title:  Visit
        link_bttn_url: https://example.com
        link_bttn_class: bttn bttn--full bttn--outline bttn--secondary__light
        link_bttn_icon:
      - link_bttn_title: Apply
        link_bttn_url: https://example.com
        link_bttn_class: bttn bttn--full bttn--outline bttn--secondary__light
        link_bttn_icon:
    link_icon:
      items:
      - link_icon_title: Facebook
        link_icon_url: https://example.com
        link_icon_class: fab fa-facebook-square
      - link_icon_title:  Twitter
        link_icon_url: https://example.com
        link_icon_class: fab fa-twitter-square
        link_bttn_icon: fab fa-twitter-square
      - link_icon_title: Instagram
        link_icon_url: https://example.com
        link_icon_class: fab fa-instagram
      - link_icon_title: Snapchat
        link_icon_url: https://example.com
        link_icon_class: fab fa-snapchat
      - link_icon_title: Youtube
        link_icon_url: https://example.com
        link_icon_class: fab fa-youtube
      - link_icon_title: LinkedIn
        link_icon_url: https://example.com
        link_icon_class: fab fa-linkedin
      - link_icon_title: Pinterest
        link_icon_url: https://example.com
        link_icon_class: fab fa-pinterest
    links_nav_1:
      links:
      - link_nav_text:
        links:
        - link_nav_text: Emergency Info
          link_nav_url: '#'
        - link_nav_text: Campus Safety
          link_nav_url: '#'
        - link_nav_text: Maps
          link_nav_url: '#'
        - link_nav_text: Directory
          link_nav_url: '#'
        - link_nav_text: A-Z Search
          link_nav_url: '#'
    links_nav_2:
      links:
      - link_nav_text:
        links:
        - link_nav_text: Privacy
          link_nav_url: '#'
        - link_nav_text: Accessibility
          link_nav_url: '#'
        - link_nav_text: Nondiscrimination
          link_nav_url: '#'
        - link_nav_text: Contact
          link_nav_url: '#'

variants:
  - name: default
    label: Home Page
    hidden: false
  - name: College
    label: College
    hidden: false
    context:
      site_name: College of Law
      site_slogan:
      footer_type: department
  - name: Department
    label: Department
    hidden: false
    context:
      site_name: College of Law
      site_slogan: Department of Admissions
      footer_type: department
  - name: links-bttn
    label: Footer Links Bttn
    hidden: true
  - name: links-icon
    label: Footer Links Icon
    hidden: true
  - name: links-nav
    label: Footer Links Nav
    hidden: true
