title: Footer
hidden: false
order: 9
status: wip
context:
  footer_logo: ../../images/uiowa-secondary.svg#logo
  footer_type: uiowa
  link_bttn:
    items:
      - link_bttn_title: Apply
        link_bttn_url: https://uiowa.edu/
        link_bttn_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps
        link_bttn_icon: fas fa-info-circle
      - link_bttn_title:  Visit
        link_bttn_url: https://uiowa.edu/
        link_bttn_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps
        link_bttn_icon: fas fa-map-marker-alt
      - link_bttn_title: Request Info
        link_bttn_url: https://uiowa.edu/
        link_bttn_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps
        link_bttn_icon: fas fa-pencil-alt
      - link_bttn_title: Jobs
        link_bttn_url: https://uiowa.edu/
        link_bttn_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps
        link_bttn_icon: fas fa-folder
  link_icon:
    items:
      - text: Facebook
        url: https://uiowa.edu/
        icon_class: fab fa-facebook-square
      - text:  Twitter
        url: https://uiowa.edu/
        icon_class: fab fa-twitter-square
      - text: Instagram
        url: https://uiowa.edu/
        icon_class: fab fa-instagram
      - text: Snapchat
        url: https://uiowa.edu/
        icon_class: fab fa-snapchat
      - text: Youtube
        url: https://uiowa.edu/
        icon_class: fab fa-youtube
      - text: LinkedIn
        url: https://uiowa.edu/
        icon_class: fab fa-linkedin
      - text: Pinterest
        url: https://uiowa.edu/
        icon_class: fab fa-pinterest
  links_nav_1:
    items:
      - text: About Iowa
        url: '#'
      - text: MyUI
        url: '#'
      - text: Jobs@Iowa
        url: '#'
      - text: Human resources
        url: '#'
      - text: Student health
        url: '#'
      - text: Libraries
        url: '#'
      - text: Course catalog
        url: '#'
      - text: Academic calendars
  links_nav_2:
    items:
      - text: Emergency Info
        url: '#'
      - text: Campus Safety
        url: '#'
      - text: Maps
        url: '#'
      - text: Directory
        url: '#'
      - text: A-Z Search
        url: '#'
  links_nav_3:
    items:
      - text: Privacy
        url: '#'
      - text: Accessibility
        url: '#'
      - text: Nondiscrimination
        url: '#'
      - text: Contact
        url: '#'

variants:
  - name: default
    label: Home Page
    hidden: false
  - name: College
    label: College
    hidden: false
    context:
      site_name: College of Law
      site_slogan:
      footer_type: department
  - name: Department
    label: Department
    hidden: false
    context:
      site_name: College of Law
      site_slogan: Department of Admissions
      footer_type: department
  - name: contact-info
    label: Footer Contact Info
    hidden: true
  - name: links-bttn
    label: Footer Links Bttn
    hidden: true
  - name: socket-menu
    label: Footer Socket Menu
    hidden: true
