title: Off Canvas Menu
hidden: false
order: 4
status: wip

variants:
  - name: default
    label: Off Canvas
    hidden: false
    context:
      site_name:
      site_slogan:
      site_front:
      site_title:
      site_nav: off-canvas
      top_nav: uiowa
      header_classes: main-iowa
      menu_path_1: ../../images/menu-01.svg#menu
      menu_path_2: ../../images/search-01.svg#search
      menu_path_3: ../../images/close-01.svg#close
      menu_path_4: ../../images/m-s-01.svg#menu-search
  - name: Site Name
    label: Site Name
    hidden: false
    context:
      site_name: Carver College of Medicine
      site_slogan:
      site_front:
      site_title:
      site_nav: off-canvas
      top_nav: 'false'
      header_classes: top-iowa
  - name: Horizontal Nav
    label: Horizontal Nav
    hidden: false
    context:
      site_name: Carver College of Medicine
      site_slogan:
      site_front:
      site_title:
      site_nav: horizontal
      top_nav: 'false'
      header_classes: sub-menu
  - name: Department Nav
    label: Department Nav
    hidden: false
    context:
      site_name: Fraternal Order of Eagles Diabetes Research Center
      site_slogan: Carver College of Medicine
      site_front:
      site_title:
      site_nav: department
      site_subnav: subnav-false
      top_nav: 'true'
      header_classes: dept-menu
  - name: Department Nav Horizontal
    label: Department Nav Horizontal
    hidden: false
    context:
      site_name: Fraternal Order of Eagles Diabetes Research Center
      site_slogan: Carver College of Medicine
      site_front:
      site_title:
      site_nav: department
      site_subnav: subnav-true
      top_nav: department
      header_classes: dept-menu

