title: Off Canvas Menu
hidden: false
order: 4
status: wip

variants:
  - name: default
    label: Off Canvas
    hidden: false
    context:
      site_name:
      site_slogan:
      site_front:
      site_title:
      site_nav: off-canvas
      top_nav: 'true'
  - name: Site Name
    label: Site Name
    hidden: false
    context:
      site_name: Undergraduate Admissions
      site_slogan:
      site_front:
      site_title:
      site_nav: off-canvas
      top_nav: 'false'
  - name: Horizontal Nav
    label: Horizontal Nav
    hidden: false
    context:
      site_name: Undergraduate Admissions
      site_slogan:
      site_front:
      site_title:
      site_nav: horizontal
      top_nav: 'false'
