title: IOWA Bar
context:
  site_name: Site Name
  site_name_position: inline
variants:
  - name: default
    label: Just Logo
    context:
      site_name: ''
  - name: full
    label: Full
    context:
      iowa_bar_classes: 'iowa-bar--full'
  - name: narrow
    label: Narrow
    context:
      iowa_bar_classes: 'iowa-bar--narrow'
  - name: site_name_below
    label: Site name below
    context:
      site_name_position: below