title: IOWA Bar
context:
  site_name: Site Name
variants:
  - name: default
    label: Just Logo
    context:
      site_name: ''
  - name: full
    label: Full
    context:
      iowa_bar_classes: 'iowa-bar--full'
  - name: narrow
    label: Narrow
    context:
      iowa_bar_classes: 'iowa-bar--narrow'