label: Logo
order: 6
hidden: false
collated: true
context:
    logo_path: ../../images/uiowa-secondary.svg#logo
    logo_path_png: ../../images/uiowa-primary.png
    logo_color: logo-icon--secondary
    path: https://www.uiowa.edu

variants:
  - name: default
    label: Block IOWA
    hidden: false

  - name: tab
    label: Tab
    hidden: false
    context:
      logo_classes: logo--tab
