label: UIOWA Apply Button
hidden: true
collated: true
status: wip
order: 7
context:
    btn_color: bttn--primary
variants:
  - name: Black Background
    hidden: true
    context:
      btn_color: bttn--secondary
