title: Parent Site Name
order: 9
status: wip
hidden: true
context:
    site_name: Site Name
    site_slogan: Site Slogan
    site_slogan_link: '#'
    site_front: /
    site_title: Home Page
variants:
  - name: Department Name
    hidden: true
    context:
      site_name: Department of College
      site_slogan: College Name

