title: Icon Block
hidden: true
order: 2.5
status: wip
context:
  icons:
    items:
      - icon_title: Areas of Study
        icon_link: https://example.com
        icon_image: ../../images/stack-of-books.svg#icon
      - icon_title: Cost and Aid
        icon_link: https://example.com
        icon_image: ../../images/scholarship.svg#icon
      - icon_title: Visit Campus
        icon_link: https://example.com
        icon_image: ../../images/map-pin.svg#icon
      - icon_title: Apply Now
        icon_link: https://example.com
        icon_image: ../../images/paper.svg#icon
