title: Internal Navigation - Horizontal
hidden: false
order: 4
status: wip
context:
  field_title: Headline
  menu_type: main
  site_type: primary
  nav_classes: 'uids-menu main--secondary--horizontal'
  items:
    - class: 'menu-item'
      link:
        text: Undergraduate Admissions
        url: '#'
    - class: 'menu-item'
      link:
        text: Graduate Admissions
        url: '#'
    - class: 'menu-item'
      link:
        text: International Students
        url: '#'
    - class: 'menu-item'
      link:
        text: Online Instruction
        url: '#'
    - class: 'menu-item'
      link:
        text: Cost and Aid
        url: '#'
variants:
  - name: Internal Navigation - Vertical
    context:
      nav_classes: 'uids-menu main--secondary--vertical'
