title: CTA Block
order: 3
status: wip
hidden: false
name: CTA Block
context:
    cta_title: Create Your Path
    cta_summary: Iowa blends leadership in the arts with pioneering scientific research, helping students carve their own unique path–wherever it leads.
    cta_link_url: https://uiowa.edu/
    cta_link_title: Request Information
    cta_link_classes:
