title: Headers
hidden: true
order: 10
status: wip
context:
  site_name: Department of College
  site_slogan: College Name
  site_front: /
  site_title: Home Page
  header_alignment: site-header__default
  menu_type: superfish
  site_type: primary
  header_type: site-header--secondary
  nav_type: navbar--secondary
variants:
  - name: default
    label: Default Secondary Superfish
    hidden: true
  - name: Default Primary Superfish
    hidden: true
    context:
      header_alignment: site-header__default
      menu_type: superfish
      site_type: secondary
      header_type: site-header--primary
      nav_type: navbar--primary
  - name: Default Tertiary Superfish
    hidden: true
    context:
      header_alignment: site-header__default
      menu_type: superfish
      site_type: secondary
      header_type: site-header--tertiary
      nav_type: navbar--primary
  - name: Aligned Left Secondary Superfish
    hidden: true
    context:
      site_slogan:
      header_alignment: site-header__left
      site_type: primary
      header_type: site-header--secondary
      nav_type: navbar--secondary
  - name: Aligned Left Primary Superfish
    hidden: true
    context:
      header_alignment: site-header__left
      site_type: secondary
      header_type: site-header--primary
      nav_type: navbar--primary
  - name: Aligned Left Tertiary Superfish
    hidden: true
    context:
      header_alignment: site-header__left
      site_type: secondary
      header_type: site-header--tertiary
      nav_type: navbar--primary
  - name: Aligned Center Secondary Superfish
    context:
      header_alignment: site-header__center
      site_type: primary
  - name: Aligned Center Primary Superfish
    hidden: true
    context:
      header_alignment: site-header__center
      site_type: secondary
      header_type: site-header--primary
      nav_type: navbar--primary
  - name: Aligned Center Tertiary Superfish
    hidden: true
    context:
      header_alignment: site-header__center
      site_type: secondary
      header_type: site-header--tertiary
      nav_type: navbar--primary
  - name: Default Main Menu
    hidden: true
    context:
      header_alignment: site-header__default
      menu_type: main
      site_type: primary
  - name: Aligned Left Main Menu
    hidden: true
    context:
      header_alignment: site-header__left
      menu_type: main
      site_type: primary
  - name: Aligned Center Main Menu
    hidden: true
    context:
      header_alignment: site-header__center
      menu_type: main
      site_type: primary
  - name: UIOWA Home Page Mega Menu
    hidden: true
    context:
      header_alignment: site-header__center
      menu_type: mega
      site_type: tertiary
      header_type:
      nav_type: navbar--tertiary
