title: Statistics Block
hidden: true
order: 3
status: wip
context:
  stat_direction: 'horizontal'
  stat:
    items:
      - stat_title: '15:1'
        stat_summary: 'student-to-faculty ratio'
        stat_image: '../../images/stat-1.jpg'
        stat_image_position: 'top'
        stat_pattern:  '../../images/brain.png'
        stat_prefix:
        stat_suffix:
        stat_classes: 'uids-component--flex-center uids-component--brain'
      - stat_title: '78'
        stat_summary: 'of classes have fewer than 30 students'
        stat_image: '../../images/stat-2.jpg'
        stat_image_position: 'bottom'
        stat_pattern:  '../../images/brain.png'
        stat_prefix:
        stat_suffix: '%'
        stat_classes: 'uids-component--flex-center uids-component--brain'
      - stat_title: '34'
        stat_summary: 'best public university, u.s. news & world report'
        stat_image: '../../images/stat-3.jpg'
        stat_image_position: 'top'
        stat_pattern: '../../images/brain.png'
        stat_prefix: '#'
        stat_suffix:
        stat_classes: 'uids-component--flex-center uids-component--brain'
      - stat_title: '5,000'
        stat_summary: 'courses offered every year'
        stat_image:
        stat_pattern:
        stat_prefix: '+'
        stat_suffix:
        stat_classes: 'uids-component--flex-center uids-component--brain'

variants:
  - name: default
    hidden: false
  - name: basic
    label: Stat Block Basic
    hidden: true
