title: Statistics Block
hidden: false
order: 3
status: wip
context:
  stat_direction: 'horizontal'
  stat:
    items:
      - stat_title: '15:1'
        stat_summary: 'student-to-faculty ratio'
        stat_image: '../../images/stat-1.jpg'
        stat_image_position: 'top'
        stat_pattern:  '../../images/brain.png'
        stat_prefix:
        stat_suffix:
        stat_classes:
      - stat_title: '78'
        stat_summary: 'of classes have fewer than 30 students'
        stat_image: '../../images/stat-2.jpg'
        stat_image_position: 'bottom'
        stat_pattern:  '../../images/brain.png'
        stat_prefix:
        stat_suffix: '%'
        stat_classes: 'suffix-super'
      - stat_title: '34'
        stat_summary: 'best public university, u.s. news & world report'
        stat_image: '../../images/stat-3.jpg'
        stat_image_position: 'top'
        stat_pattern: '../../images/brain.png'
        stat_prefix: '#'
        stat_suffix:
        stat_classes:
      - stat_title: '5,000'
        stat_summary: 'courses offered every year'
        stat_image:
        stat_pattern:
        stat_prefix: '+'
        stat_suffix:
        stat_classes: '../../images/feature3.jpg'

variants:
  - name: default
    hidden: false
  - name: vertical2
    label: Statistics Block 2 Vertical
    context:
      stat_items: '2'
      stat_direction:
      stat:
        items:
          - stat_title: '78'
            stat_summary: 'of classes have fewer than 30 students'
            stat_image:
            stat_pattern:
            stat_prefix:
            stat_suffix: '%'
            stat_classes: 'stat__grid--centered'
          - stat_title: '95'
            stat_summary: 'job/grad school placement rate'
            stat_image:
            stat_pattern:
            stat_prefix:
            stat_suffix: '%'
            stat_classes: 'stat__grid--left'
  - name: advanced
    label: Stat Block Advanced
    hidden: true

  - name: basic
    label: Stat Block Basic
    hidden: true
