title: Headline
order: 2
status: wip
collated: true

variants:
  - name: default
    label: Headline
    hidden: false
    context:
      headline_level: h2
      headline_title: Bold Headline
      headline_type: bold-headline bold-headline--caps
      background_type:
  - name: Bold Headline Reversed
    hidden: false
    context:
      headline_level: h2
      headline_title: Bold Headline Serif
      headline_type: bold-headline bold-headline--serif
      background_type:

