title: Slider
hidden: false
order: 3
status: wip
meta:
  dependencies:
    stylesheets:
      - /components/banner/banner.css
      - /components/headline/headline.css
      - /components/button/button.css
variants:
  - name: default
    label: 3 Slides
    hidden: false
    context:
      feature_type: image
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: '../../../assets/images/examples/feature1.jpg'
            feature_banner_class: banner--reversed
            feature_expanded: true
          - feature_title: 2019 Graduates
            feature_sub: Receiving a diploma signals both an ending and a beginning
            feature_banner_image: '../../../assets/images/examples/feature2.jpg'
            feature_banner_class: banner--reversed
          - feature_title: Turning the Tide
            feature_sub: Alumna Lauren Palmer aims to rehabilitate animals
            feature_banner_image: '../../../assets/images/examples/feature3.jpg'
            feature_link: https://example3.com
            feature_link_title: Read More
            feature_link_class: bttn bttn--primary bttn--caps
            feature_banner_class: banner--reversed
  - name: 2_slides
    label: 2 Slides
    hidden: false
    context:
      feature_type: image
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: '../../../assets/images/examples/feature1.jpg'
            feature_link: https://example.com
            feature_link_title: Read More
            feature_link_class: bttn bttn--primary bttn--caps
            feature_banner_class: banner--reversed
            feature_expanded: true
          - feature_title: 2019 Graduates
            feature_sub: Receiving a diploma signals both an ending and a beginning
            feature_banner_image: '../../../assets/images/examples/feature2.jpg'
            feature_link: https://example.com
            feature_link_title: Read More
            feature_link_class: bttn bttn--primary bttn--caps
            feature_banner_class: banner--reversed
  - name: 1_slide
    label: Fallback
    context:
      feature_type: image
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: '../../../assets/images/examples/feature3.jpg'
            feature_link: https://example.com
            feature_link_title: Read More
            feature_link_class: bttn bttn--primary bttn--caps
            feature_banner_class: banner--reversed
            feature_expanded: true
  - name: slide
    hidden: true
