# This is a basic workflow to help you get started with Actions

name: Publish to GitHub Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches-ignore:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: test-branch # @todo Change this before the PR is merged.

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Get the version
        id: get_version
        run: echo ::set-env name=BRANCH::${GITHUB_REF#refs/*/}

      - name: Setup node
        uses: actions/setup-node@v2.1.0
        with:
          node-version: "12.x"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run docs
      - run: echo "${{ github.ref }}"

      # https://github.com/JamesIves/github-pages-deploy-action#readme
#      - name: Deploy 🚀
#        uses: JamesIves/github-pages-deploy-action@releases/v3
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BRANCH: ${{ env.TARGET_BRANCH }} # The branch the action should deploy to.
#          FOLDER: www # The folder the action should deploy.
#          TARGET_FOLDER: branches/${{ env.BRANCH }}

